<root>
    <window_x>0</window_x>
    <window_y>0</window_y>
    <window_w>1024</window_w>
    <window_h>768</window_h>
    <fullscreen>false</fullscreen>
    <volumn_master>5</volumn_master>
    <volumn_music>10</volumn_music>
    <volumn_sfx>10</volumn_sfx>
</root>
