<root>
    <window_x>112</window_x>
    <window_y>75</window_y>
    <window_w>1600</window_w>
    <window_h>900</window_h>
    <fullscreen>false</fullscreen>
    <volumn_master>5</volumn_master>
    <volumn_music>10</volumn_music>
    <volumn_sfx>10</volumn_sfx>
</root>
